os:
- osx
- linux
osx_image: xcode8
addons:
  apt:
    packages:
      - xvfb
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "7"
matrix:
  fast_finish: true
  include:
    - os: osx
      node_js: "6"
  exclude:
    - os: osx
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install phantomjs;
    fi
  - npm config set spin false
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - travis_retry npm install
before_script:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run lint;
    fi
script:
  - npm run test
